---
title: Modelo Conceptual
---
classDiagram

                            direction RL
                                     
                            class Declaracion {
                                +generarTextoDeclaracion()
                                +exportarDeclaracion()
                            }
                    
                            class Proyecto {
                                -String metodologia
                            }
                    
                            class MiembroEquipo {
                                -String nombre
                                -String rol
                            }

                            class Fase {
                                -String nombre
                            }
                            
                            class Tarea {
                                -String descripcion
                            }

                            class HerramientaIA {
                                -String nombre
                                -String version 
                            }

                            Proyecto "1" -- "1" Declaracion : describe un
                            MiembroEquipo "1..*" -- "1" Proyecto : tiene
                            Fase "1..*" -- "1" Proyecto : se organiza en
                            Tarea "1..*" -- "1" Fase : abarca
                            HerramientaIA "1..*" -- "1..*" Tarea : se apoya en