@startuml Ejemplo
    class Declaracion {
        +generarTextoDeclaracion()
        +exportarDeclaracion()
    }


    class Proyecto {
        -metodologia: string
    }


    class MiembroEquipo {
        -nombre: string
        -rol: string
    }


    class Fase {
        -nombre: string
    }


    class Tarea {
        -descripcion: string
    }


    class HerramientaIA {
        -nombre: string
        -version: string
    }


    Declaracion "1" -- "1" Proyecto : describe un
    Proyecto "1" -- "1..*" MiembroEquipo : tiene
    Proyecto "1" -- "1..*" Fase : se organiza en
    Fase "1" -- "1..*" Tarea : abarca
    Tarea "1..*" -- "1..*" HerramientaIA : se apoya en
@enduml